---
title: "Churn Modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
# Load libraries
library(tidyverse)
library(tidymodels)
library(rsample)
library(gridExtra)
library(cowplot)
library(themis)
library(glmnet)
library(ranger)
```

```{r}
# Load custom functions
retrieve_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}
```


```{r, message=FALSE, warning=FALSE}
# Read in data
churn.raw <- read_csv("data/Churn_Modelling.csv") %>%
  
  # Eliminating the one and only row with NA values which includes outcome
  dplyr::filter(complete.cases(.))
```

```{r}
# Test/train split
set.seed(1776)
churn.split <- initial_split(churn.raw)

# Extract training/testing data
churn.training <- training(churn.split)
churn.testing <- testing(churn.split)

# Create cross validation set
churn.cv <- vfold_cv(churn.training, v = 10)
```

```{r}
# Save data
saveRDS(churn.training, file = "data/churn_training.rds")
saveRDS(churn.testing, file = "data/churn_testing.rds")
saveRDS(churn.cv, file = "data/churn_cv.rds")
```

```{r, fig.align="center"}
# Examine class balance
churn.training %>% 
  summarise(Churn = sum(Exited, na.rm = T)) %>% 
  mutate(Retained = nrow(churn.training) - Churn) %>% 
  pivot_longer(., cols = one_of("Churn", "Retained"),
               names_to = "Result",
               values_to = "Value"
               ) %>% 
  ggplot(., aes(x = Result, y = Value, fill = Result)) +
    geom_bar(stat = "identity", 
             width = 0.5) +
    theme_classic() +
    theme(legend.position = "none",
          panel.background = element_rect(fill = "#000015"),
          plot.background = element_rect(fill = "#000015"),
          text = element_text(colour = "#b3b3b3"),
          axis.text = element_text(colour = "#b3b3b3"),
          axis.line = element_blank(),
          plot.title = element_text(hjust = 0.5)) +
    scale_y_continuous(labels = scales::comma) +
    scale_fill_manual(values = c("#ff6600", "#3399ff")) +
    ggtitle(label = "Moderate Class Imbalance")
```

```{r, include=FALSE}
# Select columns needed for graphing
class.seperation <- churn.training %>% 
  dplyr::select(one_of("CreditScore",
                       "Age",
                       "Exited",
                       "Balance",
                       "EstimatedSalary")) %>% 
  mutate(Churned = ifelse(Exited == 1, "Yes", "No")) %>% 
  dplyr::filter(complete.cases(.))

# Graph 1
g1 <- ggplot(class.seperation, aes(x = Age,
                                   y = EstimatedSalary,
                                   color = Churned,
                                   alpha = .05)) +
  geom_point() +
  theme_classic() +
  theme(legend.background = element_rect(fill = "#000015"),
        legend.position = "top",
        panel.background = element_rect(fill = "#000015"),
        plot.background = element_rect(fill = "#000015"),
        text = element_text(colour = "#b3b3b3"),
        axis.text = element_text(colour = "#b3b3b3"),
        axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#ff6600", "#3399ff")) +
  ggtitle(label = "Salary vs. Age") + 
  guides(alpha = FALSE,
         color = guide_legend(reverse = T))

# Retrieve legend for graphs
legend <- retrieve_legend(g1)

# Remove legend for Graph 1
g1 <- g1 + theme(legend.position = "none")

# Graph 2
g2 <- ggplot(class.seperation, aes(x = Age,
                                   y = CreditScore,
                                   color = Churned,
                                   alpha = 0.5)) +
  geom_point() +
  theme_classic() +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#000015"),
        plot.background = element_rect(fill = "#000015"),
        text = element_text(colour = "#b3b3b3"),
        axis.text = element_text(colour = "#b3b3b3"),
        axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#ff6600", "#3399ff")) +
  ggtitle(label = "Credit Score vs. Age") +
  guides(alpha = FALSE)

# Graph 3
g3 <- ggplot(class.seperation, aes(x = Age,
                                   y = Balance,
                                   color = Churned,
                                   alpha = 0.5)) +
  geom_point() +
  theme_classic() +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#000015"),
        plot.background = element_rect(fill = "#000015"),
        text = element_text(colour = "#b3b3b3"),
        axis.text = element_text(colour = "#b3b3b3"),
        axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#ff6600", "#3399ff")) +
  ggtitle(label = "Balance vs. Age") +
  guides(alpha = FALSE)

# Graph 4
g4 <- ggplot(class.seperation, aes(x = CreditScore,
                                   y = Balance,
                                   color = Churned,
                                   alpha = 0.5)) +
  geom_point() +
  theme_classic() +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#000015"),
        plot.background = element_rect(fill = "#000015"),
        text = element_text(colour = "#b3b3b3"),
        axis.text = element_text(colour = "#b3b3b3"),
        axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("#ff6600", "#3399ff")) +
  ggtitle(label = "Credit Score vs. Balance") +
  guides(alpha = FALSE)

# Create grid for graphs
grid <- grid.arrange(g1, g2, g3, g4, legend,
                     nrow = 3, 
                     ncol = 2,
                     layout_matrix = rbind(c(1,2), c(3,4), c(5,5)),
                     widths = c(2.7, 2.7),
                     heights = c(2.5, 2.5, .5))

grid2 <- cowplot::ggdraw(grid) +
  theme(plot.background = element_rect(fill = "#000015"))
```

```{r, fig.width=12, fig.height=8, fig.align="center"}
grid2 <- cowplot::ggdraw(grid) +
  theme(plot.background = element_rect(fill = "#000015"))

plot(grid2)
```

```{r}
# Define the recipe
churn.recipe <- recipe(Exited ~ ., 
                       data = head(churn.training)) %>% 
  
  # Carry's non-predictors through model
  update_role(RowNumber, CustomerId, Surname, new_role = "Helper") %>% 
  
  # Convert outcome to nominal
  step_num2factor(all_outcomes(), 
                  levels = c("No", "Yes"),
                  transform = function(x) {x + 1}) %>% 
  
  # Scale and Center Data
  step_normalize(all_numeric()) %>% 
  
  # Create dummy variables for nominal predictors
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  
  # Remove correlated and near zero predictors
  step_corr(all_numeric()) %>% 
  step_nzv(all_predictors()) %>% 
  
  # Deal with class imbalance
  step_smote(Exited)
```

```{r}
# Create glmnet model
glmnet.mod <- logistic_reg(
      penalty = tune(),
      mixture = tune(),
      mode = "classification") %>% 
  set_engine("glmnet")

# Create Hyperparameter Grid for glmnet model
glmnet.grid <- glmnet.mod %>% 
      parameters() %>% 
      grid_max_entropy(size = 50)
```

```{r}
# Create Random Forest Model
rf_mod <- rand_forest(
      mode = "classification",
      mtry = tune(),
      min_n = tune(),
      trees = tune()) %>% 
  set_engine("ranger")

# Create Hyperparameter Grid for random forest model
rf.grid <- rf_mod %>% 
  parameters() %>% 
  update(mtry = mtry(c(1L, 5L)),
         trees = trees(c(200L, 500L)) )%>% 
  grid_max_entropy(size = 50)
```

```{r}
# Fit Workflows
glmnet.wrkflw <- workflow() %>% 
  add_recipe(churn.recipe) %>% 
  add_model(glmnet.mod)

rf.wrkflw <- workflow() %>% 
  add_recipe(churn.recipe) %>% 
  add_model(rf_mod)
```

```{r}
# Tune models over cv sets
glmnet.wrkflow.tuned <- glmnet.wrkflw %>% 
  tune_grid(resamples = churn.cv,
            grid = glmnet.grid,
            metrics = metric_set(accuracy, roc_auc))
saveRDS(glmnet.wrkflow.tuned, file = "models/glmnet_wrkflw_tuned")

rf.wrkflw.tuned <- rf.wrkflw %>% 
  tune_grid(resamples = churn.cv,
            grid = rf.grid,
            metrics = metric_set(accuracy, roc_auc))
```

```{r}
glmnet.wrkflow.tuned %>% 
  show_best(metric = "roc_auc")
```








