---
title: "Churn Modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
# Load libraries
library(tidyverse)
library(tidymodels)
library(rsample)
library(glmnet)
library(ranger)
library(dials)
library(tune)
library(workflows)
library(readr)
library(xgboost)
library(kernlab)
```

```{r}
# Load cross validation data
churn.cv <- read_rds("../data/churn_cv.rds")
```

```{r}
# Load recipes
churn.recipe.no <- read_rds("../models/churn_recipe_none.rds")
churn.recipe.sm <- read_rds("../models/churn_recipe_smote.rds")
churn.recipe.rose <- read_rds("../models/churn_recipe_rose.rds")
churn.recipe.up <- read_rds("../models/churn_recipe_up_sampling.rds")
```

```{r}
# Load models
glmnet.mod <- read_rds("../models/glmnet_mod.rds")
rf.mod <- read_rds("../models/rf_mod.rds")
xgb.mod <- read_rds("../models/xgb_mod.rds")
svm.mod <- read_rds("../models/svm_mod.rds")
```

```{r}
# Load tuning grids
glmnet.grid <- read_rds("../models/glmnet_grid.rds")
rf.grid <- read_rds("../models/rf_grid.rds")
xgb.grid <- read_rds("../models/xgb_grid.rds")
svm.grid <- read_rds("../models/svm_grid.rds")
```

```{r}
# Fit Workflows

######## glmnet workflows ########

# No class imbalance method
glmnet.wrkflw.no <- workflow() %>% 
  add_recipe(churn.recipe.no) %>% 
  add_model(glmnet.mod)

# Smote
glmnet.wrkflw.sm <- glmnet.wrkflw.no %>% 
  update_recipe(churn.recipe.sm)

# Rose
glmnet.wrkflw.rose <- glmnet.wrkflw.no %>% 
  update_recipe(churn.recipe.rose)

# Up-sampling
glmnet.wrkflw.up <- glmnet.wrkflw.no %>% 
  update_recipe(churn.recipe.up)

######## rf workflows ########

# No class imbalance method
rf.wrkflw.no <- workflow() %>% 
  add_recipe(churn.recipe.no) %>% 
  add_model(rf.mod)

# Smote
rf.wrkflw.sm <- rf.wrkflw.no %>% 
  update_recipe(churn.recipe.sm)

# Rose
rf.wrkflw.rose <- rf.wrkflw.no %>% 
  update_recipe(churn.recipe.rose)

# Up-sampling
rf.wrkflw.up <- rf.wrkflw.no %>% 
  update_recipe(churn.recipe.up)

######## xgb workflows ########

# No class imbalance method
xgb.wrkflw.no <- workflow() %>% 
  add_recipe(churn.recipe.no) %>% 
  add_model(xgb.mod)

# Smote
xgb.wrkflw.sm <- xgb.wrkflw.no %>% 
  update_recipe(churn.recipe.sm)

# Rose
xgb.wrkflw.rose <- xgb.wrkflw.no %>% 
  update_recipe(churn.recipe.rose)

# Up-sampling
xgb.wrkflw.up <- xgb.wrkflw.no %>% 
  update_recipe(churn.recipe.up)

######## svm workflows ########

# No class imbalance method
svm.wrkflw.no <- workflow() %>% 
  add_recipe(churn.recipe.no) %>% 
  add_model(svm.mod)

# Smote
svm.wrkflw.sm <- svm.wrkflw.no %>% 
  update_recipe(churn.recipe.sm)

# Rose
svm.wrkflw.rose <- svm.wrkflw.no %>% 
  update_recipe(churn.recipe.rose)

# Up-sampling
svm.wrkflw.up <- svm.wrkflw.no %>% 
  update_recipe(churn.recipe.up)
```

Model tuning is split into two chunks due to run time.

```{r}
# Tune models over cv sets for glmnet and rf
set.seed(12)

# Glmnet Models
glmnet.wrkflw.tuned.no <- glmnet.wrkflw.no %>% 
  tune_grid(resamples = churn.cv,
            grid = glmnet.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

glmnet.wrkflw.tuned.sm <- glmnet.wrkflw.sm %>% 
  tune_grid(resamples = churn.cv,
            grid = glmnet.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

glmnet.wrkflw.tuned.rose <- glmnet.wrkflw.rose %>% 
  tune_grid(resamples = churn.cv,
            grid = glmnet.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

glmnet.wrkflw.tuned.up <- glmnet.wrkflw.up %>% 
  tune_grid(resamples = churn.cv,
            grid = glmnet.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

# Random Forrest Models
rf.wrkflw.tuned.no <- rf.wrkflw.no %>% 
  tune_grid(resamples = churn.cv,
            grid = rf.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

rf.wrkflw.tuned.sm <- rf.wrkflw.sm %>% 
  tune_grid(resamples = churn.cv,
            grid = rf.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

rf.wrkflw.tuned.rose <- rf.wrkflw.rose %>% 
  tune_grid(resamples = churn.cv,
            grid = rf.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

rf.wrkflw.tuned.up <- rf.wrkflw.up %>% 
  tune_grid(resamples = churn.cv,
            grid = rf.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))
```

```{r}
# saveRDS(glmnet.wrkflw.tuned.no, "../models/glmnet_wrkflw_tuned_none.rds")
# saveRDS(glmnet.wrkflw.tuned.sm, "../models/glmnet_wrkflw_tuned_smote.rds")
# saveRDS(glmnet.wrkflw.tuned.rose, "../models/glmnet_wrkflw_tuned_rose.rds")
# saveRDS(glmnet.wrkflw.tuned.up, "../models/glmnet_wrkflw_tuned_up.rds")
# saveRDS(rf.wrkflw.tuned.no, "../models/rf_wrkflw_tuned_none.rds")
# saveRDS(rf.wrkflw.tuned.sm, "../models/rf_wrkflw_tuned_smote.rds")
# saveRDS(rf.wrkflw.tuned.rose, "../models/rf_wrkflw_tuned_rose.rds")
# saveRDS(rf.wrkflw.tuned.up, "../models/rf_wrkflw_tuned_up.rds")
```

```{r}
# Tune models over cv sets for xgboost and svm
set.seed(12)

# XGB Models
xgb.wrkflw.tuned.no <- xgb.wrkflw.no %>% 
  tune_grid(resamples = churn.cv,
            grid = xgb.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

xgb.wrkflw.tuned.sm <- xgb.wrkflw.sm %>% 
  tune_grid(resamples = churn.cv,
            grid = xgb.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

xgb.wrkflw.tuned.rose <- xgb.wrkflw.rose %>% 
  tune_grid(resamples = churn.cv,
            grid = xgb.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

xgb.wrkflw.tuned.up <- xgb.wrkflw.up %>% 
  tune_grid(resamples = churn.cv,
            grid = xgb.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

# SVM Models
svm.wrkflw.tuned.no <- svm.wrkflw.no %>% 
  tune_grid(resamples = churn.cv,
            grid = svm.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

svm.wrkflw.tuned.sm <- svm.wrkflw.sm %>% 
  tune_grid(resamples = churn.cv,
            grid = svm.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

svm.wrkflw.tuned.rose <- svm.wrkflw.rose %>% 
  tune_grid(resamples = churn.cv,
            grid = svm.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))

svm.wrkflw.tuned.up <- svm.wrkflw.up %>% 
  tune_grid(resamples = churn.cv,
            grid = svm.grid,
            metrics = metric_set(accuracy, roc_auc),
            control = control_grid(verbose = TRUE))
```

```{r}
# saveRDS(xgb.wrkflw.tuned.no, "../models/xgb_wrkflw_tuned_none.rds")
# saveRDS(xgb.wrkflw.tuned.sm, "../models/xgb_wrkflw_tuned_smote.rds")
# saveRDS(xgb.wrkflw.tuned.rose, "../models/xgb_wrkflw_tuned_rose.rds")
# saveRDS(xgb.wrkflw.tuned.up, "../models/xbg_wrkflw_tuned_up.rds")
# saveRDS(svm.wrkflw.tuned.no, "../models/svm_wrkflw_tuned_none.rds")
# saveRDS(svm.wrkflw.tuned.sm, "../models/svm_wrkflw_tuned_smote.rds")
# saveRDS(svm.wrkflw.tuned.rose, "../models/svm_wrkflw_tuned_rose.rds")
# saveRDS(svm.wrkflw.tuned.up, "../models/svm_wrkflw_tuned_up.rds")
```

```{r}
rf.wrkflw.tuned.up %>% show_best(metric = "roc_auc")
```

```{r}
glmnet.wrkflw.tuned.no <- read_rds("../models/glmnet_wrkflw_tuned_none.rds")
glmnet.wrkflw.tuned.up <- read_rds("../models/glmnet_wrkflw_tuned_up.rds")
glmnet.wrkflw.tuned.sm <- read_rds("../models/glmnet_wrkflw_tuned_smote.rds")
glmnet.wrkflw.tuned.rose <- read_rds("../models/glmnet_wrkflw_tuned_rose.rds")

rf.wrkflw.tuned.no <- read_rds("../models/rf_wrkflw_tuned_none.rds")
rf.wrkflw.tuned.up <- read_rds("../models/rf_wrkflw_tuned_up.rds")
rf.wrkflw.tuned.sm <- read_rds("../models/rf_wrkflw_tuned_smote.rds")
rf.wrkflw.tuned.rose <- read_rds("../models/rf_wrkflw_tuned_rose.rds")

xgb.wrkflw.tuned.no <- read_rds("../models/xgb_wrkflw_tuned_none.rds")
xgb.wrkflw.tuned.up <- read_rds("../models/xgb_wrkflw_tuned_up.rds")
xgb.wrkflw.tuned.sm <- read_rds("../models/xgb_wrkflw_tuned_smote.rds")
xgb.wrkflw.tuned.rose <- read_rds("../models/xgb_wrkflw_tuned_rose.rds")

svm.wrkflw.tuned.no <- read_rds("../models/svm_wrkflw_tuned_none.rds")
svm.wrkflw.tuned.up <- read_rds("../models/svm_wrkflw_tuned_up.rds")
svm.wrkflw.tuned.sm <- read_rds("../models/svm_wrkflw_tuned_smote.rds")
svm.wrkflw.tuned.rose <- read_rds("../models/svm_wrkflw_tuned_rose.rds")
```


```{r}
# Table of AUC for every classification X imbalance technique combination

# Create list of models
model.list<- tibble(glmnet.wrkflw.tuned.no,
                   glmnet.wrkflw.tuned.sm,
                   glmnet.wrkflw.tuned.rose,
                   glmnet.wrkflw.tuned.up,
                   rf.wrkflw.tuned.no,
                   rf.wrkflw.tuned.sm,
                   rf.wrkflw.tuned.rose,
                   rf.wrkflw.tuned.up,
                   xgb.wrkflw.tuned.no,
                   xgb.wrkflw.tuned.sm,
                   xgb.wrkflw.tuned.rose,
                   xgb.wrkflw.tuned.up,
                   svm.wrkflw.tuned.no,
                   svm.wrkflw.tuned.sm,
                   svm.wrkflw.tuned.rose,
                   svm.wrkflw.tuned.up
                   )

# Create metric tibble for models
model.metrics.auc <- tibble(models = c(map(.x = model.list,
                                              ~show_best(.x, metric = "roc_auc", 1)))) %>% 
  unnest(models) %>% 
  mutate(model = c(rep("glment", 4),
                   rep("rf", 4),
                   rep("xgboost", 4),
                   rep("svm", 4)),
         class.imbalance = c(
           rep(c("None",
                 "Smote",
                 "Rose",
                 "Up-sampling"), 4)))

model.metrics.accuracy <- tibble(models = c(map(.x = model.list,
                                              ~show_best(.x, metric = "accuracy", 1)))) %>% 
  unnest(models) %>% 
  mutate(model = c(rep("glment", 4),
                   rep("rf", 4),
                   rep("xgboost", 4),
                   rep("svm", 4)),
         class.imbalance = c(
           rep(c("None",
                 "Smote",
                 "Rose",
                 "Up-sampling"), 4))) 

# Combine accuracy and auc tibbles for first set of models
model.metrics <- model.metrics.auc %>% 
  rbind(model.metrics.accuracy)

model.metrics
```

```{r}
cv.graph <- model.metrics %>% 
  filter(.metric == "roc_auc") %>% 
  ggplot(., aes(x = model,
                y = mean,
                color = class.imbalance)) +
  geom_point() +
  geom_line(aes(group = class.imbalance)) +
  theme_classic() +
  theme(legend.position = "bottom",
        legend.background = element_rect(fill = "#000027",
                                         colour = "#b3b3b3"),
        panel.background = element_rect(fill = "#000027"),
        plot.background = element_rect(fill = "#000027"),
        text = element_text(colour = "#b3b3b3"),
        axis.text = element_text(colour = "#b3b3b3"),
        axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  ggtitle("Top-performing Models") +
  xlab("Classifier") +
  ylab("AUC") +
  labs(color = "Imbalance Technique") +
  scale_color_manual(values = c("#ff6600", "#3399ff", "#cc0000", "#33cc33"))

# Save graph
saveRDS(cv.graph, "../graphs/cv_graph.rds")
```

```{r}
# Save params
xgb.up.params <- xgb.wrkflw.tuned.up %>% 
  select_best(metric = "roc_auc")

saveRDS(xgb.up.params, "../models/xgb_up_params.rds")
```




