---
title: "Tuning Grids"
author: "Ryan Fabricius"
date: "4/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This mardown serves to create the models and their corresponding tuning grids for the different classification methods. These will be saved here and loaded into the tune markdown. The individual grids and models will be located in the models folder.

```{r}
# Load libraries
library(dplyr)
library(tune)
library(parsnip)
```

```{r}
# Create parsnip models

# glmnet model
glmnet.mod <- logistic_reg(
      mode = "classification",
      penalty = tune(),
      mixture = tune()) %>% 
  set_engine("glmnet")

# Random Forest Model
rf.mod <- rand_forest(
      mode = "classification",
      mtry = tune(),
      min_n = tune(),
      trees = tune()) %>% 
  set_engine("ranger")

# xgboost model
xgb.mod <- boost_tree(
      mode = "classification",
      trees = tune(),
      mtry = tune(),
      min_n = tune(),
      learn_rate = tune(),
      loss_reduction = tune(),
      sample_size = tune()) %>% 
  set_engine("xgboost")

# svm model
svm.mod <- svm_rbf(
      mode = "classification",
      cost = tune(),
      rbf_sigma = tune(),
      margin = tune()) %>%
  set_engine("kernlab")
```

```{r}
# Save Models
# saveRDS(glmnet.mod, file = "../models/glmnet_mod.rds")
# saveRDS(rf.mod, file = "../models/rf_mod.rds")
# saveRDS(xgb.mod, file = "../models/xgb_mod.rds")
# saveRDS(svm.mod, file = "../models/svm_mod.rds")
```

```{r}
# Create Hyperparameter Grid for glmnet model
glmnet.grid <- glmnet.mod %>% 
      parameters() %>% 
      grid_max_entropy(size = 50)

# Create Hyperparameter Grid for random forest model
rf.grid <- rf.mod %>% 
  parameters() %>% 
  update(mtry = mtry(c(1L, 5L)),
         trees = trees(c(200L, 500L)))%>% 
  grid_max_entropy(size = 50)

# Create Hyperparameter Grid for xgboost
xgb.grid <- xgb.mod %>% 
  parameters() %>% 
  update(mtry = mtry(c(1L, 5L)),
         trees = trees(c(200L, 500L))) %>% 
  grid_max_entropy(size = 50)

# Create Hyperparameter Grid for svm
svm.grid <- svm.mod %>% 
  parameters() %>% 
  grid_max_entropy(size = 50)
```

```{r}
# Save grids
# saveRDS(glmnet.grid, file = "../models/glmnet_grid.rds")
# saveRDS(rf.grid, file = "../models/rf_grid.rds")
# saveRDS(xgb.grid, file = "../models/xgb_grid.rds")
# saveRDS(svm.grid, file = "../models/svm_grid.rds")
```

